use_frameworks! :linkage => :static
platform :ios, '12.0'
source 'https://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@github.com/elgrocer/el-grocer-shopper-sdk-iOS.git'


target 'el-grocer-shopper-sdk-iOS_Example' do
  pod 'el-grocer-shopper-sdk-iOS', :path => '../'

  target 'el-grocer-shopper-sdk-iOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
