use_frameworks! :linkage => :static
platform :ios, '12.0'

target 'el-grocer-shopper-sdk-iOS_Example' do
  pod 'el-grocer-shopper-sdk-iOS', :path => '../'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'IQKeyboardManagerSwift'
  
  
  target 'el-grocer-shopper-sdk-iOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#    if config.build_settings['WRAPPER_EXTENSION'] == 'bundle'
#            config.build_settings['DEVELOPMENT_TEAM'] = 'N883C2D2B2'
#    end
    #config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
    #config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
    #config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    #config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    
  end
end
